name: HDRMerge
author: Javier Celaya
markdown: kramdown
highlighter: rouge
baseurl: /hdrmerge
gitpagesurl: http://jcelaya.github.io/hdrmerge
description: HDR raw exposure merging
github: http://www.github.com/jcelaya/hdrmerge
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
googleplus: https://plus.google.com/108529106439895792928
email: hdrmerge[at]gmail.com
latest_release: [ Release Object ]
